### ISSUE TITLE
Not able to add new page below root

### ISSUE THREAD

**Issue by stlorenz** [million12/neos-typostrap-distribution#2]
Hi,

i just tried the typostrap distribution after sucessfully using the docker-typo3-neos Repository.
It starts w/o any problems but i am not able to add new pages below site root.
The "Insert Content" Buttom seems to have no effect. 
I can add Content to the root page itself without any problems. 
Creating another user did not help.

**Comment by ryzy** [comment]
Thanks Stefan - it must have sth to do with most recent changes (we use unreleased Neos 2.0 for Typostrap distro) and/or custom patches we apply there.

Good spot, I'm on it, will post update once it's fixed.

**Comment by stlorenz** [comment]
Hi Marcin,
thanks for your fast reply. I am really waiting for this since I am familiar with Zurb and have used in other CMS already and want to build the website for my new company with typostrap.
 But I am totally new to Neos and so my attempts to integrate it myself baldy failed. If i can help just let me know

**Comment by ryzy** [comment]
Hi Stefan!

Sorry, I completely forgot to update this ticket. But if you followed the commits, you've probably noticed it's fixed... ;) 

We've just updated it to latest Neos 2.0-dev - hope you'll enjoy it. And please do let me know if you spot any more issues. Thanks!

**Comment by stlorenz** [comment]
Hi, sorry I missed the notification too. 
I just switched to the Odoo Website Builder for getting the Site up and runnning fast but i will take another look at neos when I will set up the next iteration.
